### ISSUE TITLE
Create an agent through the lib.

### ISSUE THREAD

**Issue by kozeyandrey** [dialogflow/dialogflow-python-client#37]
Hello,

Could you please help me understand, how I can create a new agent object though this lib and if it's even possible?

Thanks!

Regards,
Andrew.

**Comment by allentv** [comment]
This might help -https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.Agent

**Comment by kozeyandrey** [comment]
Thanks!
